spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always
